// Mock channel data for testing
export const mockChannels = [
  {
    id: "ch1",
    name: "React Masters",
    handle: "@react-masters",
    description: "Advanced tutorials and insights for React developers",
    avatar: "/placeholders/avatars/react-masters.jpg",
    banner: "/placeholders/banners/react-masters.jpg",
    joinDate: "Jan 2022",
  },
  {
    id: "ch2",
    name: "Design Hub",
    handle: "@design-hub",
    description: "Creative design inspiration and tutorials",
    avatar: "/placeholders/avatars/design-hub.jpg",
    banner: "/placeholders/banners/design-hub.jpg",
    joinDate: "Mar 2022",
  },
  {
    id: "ch3",
    name: "Next.js Ninjas",
    handle: "@nextjs-ninjas",
    description: "All things Next.js and React frameworks",
    avatar: "/placeholders/avatars/nextjs-ninjas.jpg",
    banner: "/placeholders/banners/nextjs-ninjas.jpg",
    joinDate: "Jun 2022",
  },
  {
    id: "ch4",
    name: "TypeScript Pro",
    handle: "@typescript-pro",
    description: "Taking your TypeScript skills to the next level",
    avatar: "/placeholders/avatars/typescript-pro.jpg",
    banner: "/placeholders/banners/typescript-pro.jpg",
    joinDate: "Sep 2022",
  },
  {
    id: "ch5",
    name: "Coding With Julie",
    handle: "@julie-codes",
    description: "Full-stack development tutorials and tips",
    avatar: "/placeholders/avatars/julie-codes.jpg",
    banner: "/placeholders/banners/julie-codes.jpg",
    joinDate: "Nov 2022",
  },
  {
    id: "ch6",
    name: "Backend Brilliance",
    handle: "@backend-brilliance",
    description: "Server-side programming and architecture",
    avatar: "/placeholders/avatars/backend-brilliance.jpg",
    banner: "/placeholders/banners/backend-brilliance.jpg",
    joinDate: "Jan 2023",
  },
  {
    id: "ch7",
    name: "Mobile Dev Masters",
    handle: "@mobile-masters",
    description: "Cross-platform and native mobile development",
    avatar: "/placeholders/avatars/mobile-masters.jpg",
    banner: "/placeholders/banners/mobile-masters.jpg",
    joinDate: "Mar 2023",
  },
  {
    id: "ch8",
    name: "DevOps Daily",
    handle: "@devops-daily",
    description: "CI/CD, infrastructure, and DevOps practices",
    avatar: "/placeholders/avatars/devops-daily.jpg",
    banner: "/placeholders/banners/devops-daily.jpg",
    joinDate: "May 2023",
  },
]; 